title: Documentation
doc_version: 0.2.1
url: https://clutils.nlamprian.me

permalink: /:categories/:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jemoji
  - rouge
